# Build
[build]
  base = "."
  command = "rm LICENSE.txt README.md"
  publish = "."

# Headers
[[headers]]
  for = "/*"
    [headers.values]
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      X-UA-Compatible = "IE=edge,chrome=1"
      Content-Security-Policy = """
        default-src 'none';
        script-src
          'self'
          'sha256-CF70GJOpFa8VBcFVsIEOnThhun0y9+LfB/pVk8nEB98='
          https://cdn.jsdelivr.net
        ;
        style-src
          'self'
          https://cdn.jsdelivr.net
        ;
        img-src
          'self'
          data:
        ;
        font-src
          'self'
          data:
          https://cdn.jsdelivr.net
        ;
        worker-src blob:;
        connect-src data:;
        frame-ancestors *;
      """
      Permissions-Policy = """
        accelerometer=(),
        autoplay=(self),
        camera=(),
        fullscreen=(self),
        geolocation=(),
        gyroscope=(),
        interest-cohort=(),
        microphone=(),
        payment=(),
        usb=()
      """
      Access-Control-Allow-Origin = "*"
      Referrer-Policy = "no-referrer"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
      Cache-Control = "no-cache"

[[headers]]
  for = "/static/*"
    [headers.values]
      # Cache static assets for 1 month
      Cache-Control = """
        max-age=2592000,
        public
      """

[[headers]]
  for = "*.html"
    [headers.values]
      Content-Type = "text/html; charset=utf-8"

# Redirect Netlify subdomain to custom domain
[[redirects]]
  from = "https://paste-strappazzon.netlify.app/*"
  to = "https://paste.strappazzon.xyz/:splat"
  status = 301
  force = true

# 404
# Keep this redirect at the end!
[[redirects]]
  from = "/*"
  to = "/"
  status = 404
  force = false
